# Exported from Render on 2025-03-17T22:41:44Z
services:
- type: web
  name: alpha_blog-qhap
  runtime: ruby
  repo: https://github.com/Stan310/alpha-blog
  branch: alter
  plan: free
  envVars:
  - key: SECRET_KEY_BASE
    sync: false
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
version: "1"
